name: Update Readme
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - name: Compile .ts file
        run: |
          npx tsc
      - name: Update README.md
        run: |
          node tsBuild/update-readme.js
      - name: commit
        run: |
          git add .
          git config --global user.name 'WonhyeokJung'
          git config --global user.email 'wonhyeok.contact@gmail.com'
          git commit -m '[docs] auto-update README.md'
      - name: push
        run: |
          git push
          
